### ISSUE TITLE
Nickname

### ISSUE THREAD

**Issue by zFaTze** [PMExpertsDE/Server-Helper#3]
**Describe the bug**

Hallo und zwar habe ich einen Fehler gefunden, unter dem nick command.
Der Spieler aktiviert seinen Nick, aber wenn man ihn deaktiviert hat man in immer noch, weil das Plugin den Name vom Spieler nimmt und ihn auch so einstellt.

**Where did you found your bug?**
 - OS: DEBIAN
 - Plugin-Version **2.4.2**
 - PocketMine-MP/Altay Build [AKTUELL]

**Additional context**

# Thanks for your Bug-Report!

**Comment by HonorGamerHD** [comment]
der name kann also nicht richtig zurück gesetzt werden? hab ich das jetzt richtig verstanden?

**Comment by zFaTze** [comment]
Stellen sie sich vor, sie machen ihr Nick on. Aber wenn man ihn deaktiviert wird die Funktion $player->getName() benutzt sogesagt besitzt man den Nick dann noch immer, weil der Nick als/zum Default Name gestellt wird

**Comment by HonorGamerHD** [comment]
Hast du es denn getestet??

**Comment by HonorGamerHD** [comment]
Bei mir funktioniert das ganze normal, ich weiß ich was es daran zu bemängeln gibt. Von meiner Seite aus wäre das geklärt, falls es dennoch etwas gibt kommentiere einfach nochmal.
